name: unit-tests

on: pull_request

jobs:
    test-com-jest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v2
              with: 
                node-version: '21.x'
            - name: Install dependencies and run tests
              run: |
                npm install
                npm test
          

        